# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.

title: Sarma Mutturi, Principal Scientist, CSIR-CFTRI
email: smutturi.cftri@csir.res.in
google_scholar: https://scholar.google.com/citations?user=v-KxTHoAAAAJ&hl=en
orcid: http://orcid.org/0000-0002-3251-8643

description: >-
  Welcome to the personal website of Sarma Mutturi, a Principal Scientist at CSIR-CFTRI. This site
  showcases my research areas, publications, and the work of my team.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
Linkedin : https://in.linkedin.com/in/sarmamutturi
github : https://github.com/sarmamutturi

# Build settings
theme: minima
plugins:
  - jekyll-feed

# --- MINIMA NAVIGATION FIX (ADDED SECTION) ---
# This explicitly lists the pages to show in the navigation bar
header_pages:
  - Biosketch.md
  - Research Areas.md
  - Team.md
  - Publications.md
  - Software Tools.md 

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/